version: '3.8'
services:
  api:
    container_name: node_assignment
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - '5433:50000'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=PostgreSQL 15

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
 data: {}
